### PR TITLE
Using conda for RTD, clearing up config files

### PR DESCRIPTION
**Pull request by bsipocz**
I think switching to conda install should make it work.

### CODE REVIEW

**Comment by bsipocz** [comment]
Hmm, it looks like that you didn't run travis for this repo for a while ;)

**Comment by bmorris3** [comment]
Thanks for your help @bsipocz, you're my hero 🏆

**Comment by bmorris3** [comment]
Hey @bsipocz – should the new files `.rtd-environment.yml`, `readthedocs.yml` be added to the astropy package-template, and [the accompanying tutorial](http://docs.astropy.org/en/latest/development/affiliated-packages.html)? If so, I can post an issue and make a PR.

**Comment by bsipocz** [comment]
@bmorris3 - Ideally, I think, yes. However the package-template is in the middle of a major overhaul with probably moving to cookiecutter, so no rush on this.

**Comment by bmorris3** [comment]
@bsipocz Is there somewhere where I can read up on that update? I've taught a few people about the package template recently, I'd like to be able to give them warning about changes.

**Comment by bsipocz** [comment]
There was no decisions yet, see this APE https://github.com/astropy/astropy-APEs/pull/17, but if there will be changes, basically everything will be much simpler for the user.

**Pull request merged**
